### ISSUE TITLE
[BUG] operators docs is empty

### ISSUE THREAD

**Issue by schlichtanders** [JuliaGraphs/Graphs.jl#101]
**Description of bug**
When going to https://juliagraphs.org/Graphs.jl/dev/operators/ I find an empty documentation space

**How to reproduce**
just visit that website. Date:  07 February 2022

**Expected behavior**
The documentation of 1.4.0 is far more complete
https://docs.juliahub.com/Graphs/VJ6vx/1.4.0/operators/

I was expecting something similar

**Actual behavior**
no methods listed

**Comment by etiennedeg** [comment]
I reopen because this does not seem to be fixed. This is weird because it was built correctly on my computer following this fix. #99 is fixed though.
