### ISSUE TITLE
Consider mention of `SimpleGraphs`

### ISSUE THREAD

**Issue by scheinerman** [JuliaGraphs/Graphs.jl#110]
Dear developers of the JuliaGraphs ecosystem:

You have created a terrific suite of modules for handling large graphs well in Julia. The nucleus of this is the former `LightGraphs` module started by Seth Bromberger. At about the same time as Seth began this work, I created a `SimpleGraphs` module with a different design philosophy. (Alas, both your `Graphs` and my `SimpleGraphs` define a `SimpleGraph` type which makes working with both in a single session cumbersome.)

The central difference between our approaches is that the vertex set of a `Graphs` graph is always of the form `{1,2,...,n}` whereas in my `SimpleGraphs` module the vertex set can be arbitrary. For example, vertices of a cube graph are naturally expressed as a strings of `0`s and `1`s.  No doubt this makes the `Graphs` implementation more performant, but the `SimpleGraphs` implementation is more natural for mathematicians.  My modules include functions for computing the chromatic number and other such invariants that are likely to be of interest to graph theorists, whereas your high performance modules are well suited to network analysts. 

> Would you consider placing a link to my tools on your site in case your users would be interested in this alternative approach?

Thanks for considering.

**Comment by gdalle** [comment]
Hi Ed!
The JuliaGraphs webpage and documentation are currently focused on our ecosystem, that is, the set of packages that interact well with the core `Graphs.jl` library.
Do you think it would make sense for your `SimpleGraph`s to implement the [`Graphs.jl` interface](https://juliagraphs.org/Graphs.jl/dev/developing/), so that we can apply most JuliaGraphs algorithms on them?

**Comment by gdalle** [comment]
By the way, I think you may be interested in issue #35
