### ISSUE TITLE
Error in A* implementation

### ISSUE THREAD

**Issue by gdalle** [JuliaGraphs/Graphs.jl#120]
In the implementation of the [A* algorithm](https://github.com/JuliaGraphs/Graphs.jl/blob/master/src/shortestpaths/astar.jl), there is a vector called [`closed_set`](https://github.com/JuliaGraphs/Graphs.jl/blob/da30b3b255c4fb7c4f70af136cff482cac7ff411/src/shortestpaths/astar.jl#L22) which is used to indicate whether a vertex has already been expanded.

Judging by the similar notations, this implementation is taken almost as-is from the [Wikipedia page](https://en.wikipedia.org/wiki/A*_search_algorithm), but on Wikipedia the `closed_set` does not exist. In fact, the article clearly states that

>  When the heuristic being used is admissible but not consistent, it is possible for a node to be expanded by A* many times, an exponential number of times in the worst case.

Therefore, I think the presence of `closed_set` in the code is a mistake and should be corrected.

**Comment by gdalle** [comment]
@matbesancon @etiennedeg

**Comment by matbesancon** [comment]
if a vertex is expanded several times, are the following ones redundant with the first time this vertex is encountered? From your message I assume not

**Comment by gdalle** [comment]
Probably not, because this means we have found a cheaper path to said vertex, which may reveal a cheaper path to its neighbors

**Comment by matbesancon** [comment]
I'm ok with removing this. Even better if there is an example that fails to add to the tests

**Comment by captchanjack** [comment]
Hello! Just looking into this as well

Looks like the Wikipedia page you referenced **used** to have the closed_set documented in its algorithm, found a reference to an [older version](https://stackoverflow.com/questions/13578287/a-a-star-algorithm-clarification#:~:text=The%20%22Closed%20set%22%20is%20the,named%20HasBeenVisited%20or%20something%20similar.) of the page

Pretty much all the implementations I've found online use a closed_set, e.g. [python](https://github.com/jrialland/python-astar/blob/master/astar/__init__.py), [c++](https://github.com/justinhj/astar-algorithm-cpp/blob/master/cpp/stlastar.h), even this [youtube video](https://www.youtube.com/watch?v=eSOJ3ARN5FM&t=890s)

I don't really know what is correct, sources seem inconsistent...

**Comment by gdalle** [comment]
Thanks for your input! Indeed, it looks like the closed set is useful to preserve optimality in cases where the heuristic is admissible but not consistent. See the following screenshots from *Artificial Intelligence, a Modern Approach*

<img width="696" alt="Screenshot 2022-05-22 at 07 58 06" src="https://user-images.githubusercontent.com/22795598/169681110-4be4f136-6843-4159-ae6a-6c93d53a7fdd.png">
<img width="696" alt="Screenshot 2022-05-22 at 07 56 10" src="https://user-images.githubusercontent.com/22795598/169681109-55252db9-040b-4c32-b737-cf105b070cf7.png">

**Comment by gdalle** [comment]
I left the `closed_set` in #125, let's close this for now
