### ISSUE TITLE
Applying bellmanford on an arbitrary graph

### ISSUE THREAD

**Issue by coloedrainbow** [JuliaGraphs/Graphs.jl#124]
Hello,

Is it possible to apply a shortest path algorithem on an arbitray directed graph (in form of incidence matix). I went a bit through the documentation and it seems that all the implementation are valid only on adjacency matrix. How can I use bellman ford algorithem Graph.jl pakege on a matric in this format? Is that possible?
 
For exapme my network file is like the following, and the source nodes are [1, 3]
<html>
<body>

start node i | end node j | w_ij
-- | -- | --
1 | 2 | 2
1 | 3 | 5 
2 | 3 | 3 
3 | 4 | 1 
3 | 5 | 2 
4 | 1 | 0 
4 | 5 | 2 
5 | 2 | 4
5 | 3 | 2
 

</body>
</html>

**Comment by gdalle** [comment]
Hi @coloedrainbow ! If I'm not mistaken, what you have is an adjacency matrix as well, you just stored it as a list. You can use the following code to turn it into a matrix that most algorithms in Graphs.jl will accept:
```julia
using SparseArrays
I = [1, 1, 2, 3, 3, 4, 4, 5, 5]
J = [2, 3, 3, 4, 5, 1, 5, 2, 3]
W = [2, 5, 3, 1, 2, 0, 2, 4, 2]
distmx = sparse(I, J, W)
```
Let me know if it works!

**Comment by coloedrainbow** [comment]
Thak you @gdalle

`
bellman_ford_shortest_paths(g,` s, distmx=weights(g))
`

What shold I put as g then?

**Comment by gdalle** [comment]
The graph object constructed from your edge list (without the weights): see https://juliagraphs.org/Graphs.jl/dev/first_steps/construction/

**Comment by coloedrainbow** [comment]
Isn't this inefficient to have lots of zeros? (forming sparse matrix)

I've already checked that documentation, but I'm a bit lost. I don't know how to instanciate an empty `g`  to then `add_vertex!(g)`

why is this icorrect:
g = SimpleGraph(start_node, end_node)

**Comment by etiennedeg** [comment]
A sparse matrix is a specifically designed structure for storing a matrix without having to store the zeros. it is not mandatory to build a weighted graph, `SimpleWeightedGraphs.jl` uses a sparse matrix under the hood but the direct construction of the sparse matrix is also fine.
