### ISSUE TITLE
Transfer issues from LightGraphs.jl

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGraphs/Graphs.jl#18]
It's a pity to lose all the information contained in the open and closed issues of the old repo.

https://github.com/sbromberger/LightGraphs.jl/issues

**Comment by CarloLucibello** [comment]
> I tried to transfer the issues, but some are missing :

all the closed issues in LightGraphs are missing

**Comment by CarloLucibello** [comment]
> To move issues from one repository to another, apparently, we need to have the two repositories in the same organization. Maybe LightGraphs.jl can temporarily be placed in JuliaGraphs to move the issues ?

That would be ideal, but I'm not sure if LightGraphs' author wants to be involved

**Comment by ViralBShah** [comment]
At this point, we do not have the option of migrating the issues. The original repo is available - so we have a full record.
