### ISSUE TITLE
[BUG] eigenvector_centrality has erratic behavior

### ISSUE THREAD

**Issue by fargolo** [JuliaGraphs/Graphs.jl#187]
**Description of bug**
The eigenvector_centrality function has erratic behavior

**How to reproduce**

This will trow an error at every n attempts:
```
julia>using TextGraphs , Graphs
julia>poem = "Nunca a alheia vontade, inda que grata,\nCumpras por própria. Manda no que fazes,\nNem de ti mesmo servo.\nNinguém te dá quem és. Nada te mude.\nTeu íntimo destino involuntário\nCumpre alto. Sê teu filho."
julia>Graphs.eigenvector_centrality(naive_graph(poema))
```
It seems to do with **LinAlg.jl::eigs**.

_ERROR: BoundsError: attempt to access 0-element Vector{Float64} at index [1]
Stacktrace:
 [1] getindex
   @ ./array.jl:861 [inlined]
 [2] eigs(A::SparseArrays.SparseMatrixCSC{Int64, Int64}; kwargs::Base.Pairs{Symbol, Any, Tuple{Symbol, Symbol}, NamedTuple{(:which, :nev), Tuple{ArnoldiMethod.LM, Int64}}})
   @ Graphs.LinAlg ~/.julia/packages/Graphs/6MoQZ/src/linalg/LinAlg.jl:60
 [3] eigenvector_centrality(g::MetaGraphs.MetaDiGraph{Int64, Float64})
   @ Graphs ~/.julia/packages/Graphs/6MoQZ/src/centrality/eigenvector.jl:27
 [4] top-level scope_

**Expected behavior**
The function should return eigenvector centralities, as it does often.
Nonetheless, once in every n executions (~3), it returns the error above. 

**Actual behavior**
The output is erratic. Once in every n executions (~3), it returns the error above. 

**Code demonstrating bug**
Above

**Version information**
`Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, tigerlake)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = `
 
`(pkg> status Graphs
     Project TextGraphs v0.1.5
      Status `~/.../TextGraphs.jl/Project.toml`
  [86223c79] Graphs v1.7.2`

**Additional context**
It seems that the bug is related with **LinAlg.jl::eigs**:
Why does it

```
function eigs(A; kwargs...)
    schr =partialschur(A; kwargs...)
    vals, vectors = partialeigen(schr[1])
    reved = (kwargs[:which] == LR() || kwargs[:which] == LM())
    k::Int = get(kwargs, :nev, length(vals))
    k = min(k, length(vals))
    perm = collect(1:k)
    if vals[1] isa(Real)
        perm = sortperm(vals, rev=reved)
        perm = perm[1:k]
    end
    λ = vals[perm]
    Q = vectors[:, perm]
    return λ, Q
end
```

**Comment by etiennedeg** [comment]
I could not build your packages but this will be probably fixed by #84 once we review it.

**Comment by fargolo** [comment]
@etiennedeg , can you give me a feedback the building failure on TextGraphs.jl.
It seems that LinearAlgebra.jl "eigen" would be an alternative.

**Comment by aurorarossi** [comment]
I can't build TextGraphs either. Here is the error:
```
ERROR: Error building `RCall`: 
ERROR: could not load library "/usr/lib64/R/lib/libR.so"
/home/aurossi/julia-1.8.2/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /lib64/libicuuc.so.69)
ERROR: LoadError: Try adding /usr/lib64/R/lib to the "LD_LIBRARY_PATH" environmental variable and restarting Julia.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] validate_libR(libR::String)
   @ Main ~/.julia/packages/RCall/Wyd74/deps/setup.jl:26
 [3] locate_libR(Rhome::SubString{String})
   @ Main ~/.julia/packages/RCall/Wyd74/deps/setup.jl:43
 [4] top-level scope
   @ ~/.julia/packages/RCall/Wyd74/deps/build.jl:58
 [5] include(fname::String)
   @ Base.MainInclude ./client.jl:476
 [6] top-level scope
   @ none:5
in expression starting at /user/aurossi/home/.julia/packages/RCall/Wyd74/deps/build.jl:11

caused by: could not load library "/usr/lib64/R/lib/libR.so"
/home/aurossi/julia-1.8.2/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /lib64/libicuuc.so.69)
Stacktrace:
 [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
   @ Base.Libc.Libdl ./libdl.jl:117
 [2] dlopen (repeats 2 times)
   @ ./libdl.jl:116 [inlined]
 [3] validate_libR(libR::String)
   @ Main ~/.julia/packages/RCall/Wyd74/deps/setup.jl:16
 [4] locate_libR(Rhome::SubString{String})
   @ Main ~/.julia/packages/RCall/Wyd74/deps/setup.jl:43
 [5] top-level scope
   @ ~/.julia/packages/RCall/Wyd74/deps/build.jl:58
 [6] include(fname::String)
   @ Base.MainInclude ./client.jl:476
 [7] top-level scope
   @ none:5
```

**Comment by fargolo** [comment]
@aurorarossi 

It seems that R is required.
`$sudo apt install r-base` should do the trick.

R is only required for stemming, lemmatizating. 
Quite unrelated to the thread, but I wonder if it's possible to build RCall.jl only at execution-time (not when building TextGraphs.jl).


> I can't build TextGraphs either. Here is the error:
> 
> ```
> ERROR: Error building `RCall`: 
> ERROR: could not load library "/usr/lib64/R/lib/libR.so"
> /home/aurossi/julia-1.8.2/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /lib64/libicuuc.so.69)
> ERROR: LoadError: Try adding /usr/lib64/R/lib to the "LD_LIBRARY_PATH" environmental variable and restarting Julia.
> Stacktrace:
>  [1] error(s::String)
>    @ Base ./error.jl:35
>  [2] validate_libR(libR::String)
>    @ Main ~/.julia/packages/RCall/Wyd74/deps/setup.jl:26
>  [3] locate_libR(Rhome::SubString{String})
>    @ Main ~/.julia/packages/RCall/Wyd74/deps/setup.jl:43
>  [4] top-level scope
>    @ ~/.julia/packages/RCall/Wyd74/deps/build.jl:58
>  [5] include(fname::String)
>    @ Base.MainInclude ./client.jl:476
>  [6] top-level scope
>    @ none:5
> in expression starting at /user/aurossi/home/.julia/packages/RCall/Wyd74/deps/build.jl:11
> 
> caused by: could not load library "/usr/lib64/R/lib/libR.so"
> /home/aurossi/julia-1.8.2/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /lib64/libicuuc.so.69)
> Stacktrace:
>  [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
>    @ Base.Libc.Libdl ./libdl.jl:117
>  [2] dlopen (repeats 2 times)
>    @ ./libdl.jl:116 [inlined]
>  [3] validate_libR(libR::String)
>    @ Main ~/.julia/packages/RCall/Wyd74/deps/setup.jl:16
>  [4] locate_libR(Rhome::SubString{String})
>    @ Main ~/.julia/packages/RCall/Wyd74/deps/setup.jl:43
>  [5] top-level scope
>    @ ~/.julia/packages/RCall/Wyd74/deps/build.jl:58
>  [6] include(fname::String)
>    @ Base.MainInclude ./client.jl:476
>  [7] top-level scope
>    @ none:5
> ```

**Comment by gdalle** [comment]
Closing, I just ran it 100 times without issue on master
