### ISSUE TITLE
[BUG] Docs link is outdated

### ISSUE THREAD

**Issue by DarthGandalf** [JuliaGraphs/Graphs.jl#203]
**Description of bug**
The documentation link points at outdated docs.

I was searching for the graphs package in Julia, and typed graphs in the search field, so naturally found https://juliapackages.com/p/graphs
I've read the docs, understood how to implement the graph, started implementation, but got this error: `LoadError: UndefVarError: @graph_implements not defined`. Turns out that the doc I was reading was about "old" Graphs package, not the one I installed with "add Graphs" which was mentioned in the same old doc.

So I wasted time, instead of reading the correct doc.

**How to reproduce**
Detail steps to reproduce the behavior.
1. Open https://juliapackages.com/p/graphs
2. Scroll to the bottom of the page
3. Look at the docs link ("Please refer to [Graphs.jl Documentation](http://graphsjl-docs.readthedocs.org/en/latest/) for latest documentation.")

**Expected behavior**
It should point at https://juliagraphs.org/Graphs.jl/dev/

**Actual behavior**
It points at http://graphsjl-docs.readthedocs.org/en/latest/

**Comment by cormullion** [comment]
juliapackages.com is obsolete, or, at least, obsolescent. The information it presents is well over a year old, out of date and doesn't include packages created less than a year ago. I don't know whether it's been abandoned or just left to carry on until it stops working.

You could try opening (another) PR there... 🤷‍♂️ But I think juliahub.com is considered a more up to date way to find packages.
