### ISSUE TITLE
Trying to implement a new algorithm

### ISSUE THREAD

**Issue by matheusdiogenesandrade** [JuliaGraphs/Graphs.jl#207]
**Description of bug**
I am trying to implement a new algorithm for Graphs.jl, and I am facing some bugs in this task.

**How to reproduce**
Detail steps to reproduce the behavior.
1) `git clone https://github.com/JuliaGraphs/Graphs.jl.git`;
2) `cd Graphs.jl`;
3) `mkdir src/new_algorithm`;
4) `touch src/new_algorithm/new_algorithm.jl`;
5) Add the following lines to the file above:
```julia
function new_algorithm end
function new_algorithm(
   g::SimpleDiGraph{U};
   distmx::AbstractMatrix{T} = weights(g)
) where {T<:Real} where {U<:Integer}
end
```
6) `julia --project=.`;
7) `]`;
8) `(Graphs) pkg> instantiate`;
9) `Ctrl + C`;
10) Add the following lines to the file `src/Graphs.jl`, right before the last `end` keyword:
```julia
export new_algorithm
include("new_algorithm/new_algorithm.jl")
```
11) `julia> include('src/Graphs.jl')`;
12)  Create the function below:
```julia
julia> function buildGraph()
   D = Graphs.DiGraph()
   Graphs.add_vertex!(D)
   Graphs.add_vertex!(D)
   Graphs.add_vertex!(D)
   Graphs.add_vertex!(D)
   Graphs.add_edge!(D, 1, 2)
   Graphs.add_edge!(D, 2, 3)
   Graphs.add_edge!(D, 2, 4)
   Graphs.add_edge!(D, 3, 4)
   return D
end
```
13) `julia> D = buildGraph()`;
14) `julia> new_algorithm(D)`;

**Expected behavior**
No output, since the function `new_algorithm` is empty.

**Actual behavior**
Right after calling the command (14) the following message appears:
```julia
ERROR: MethodError: no method matching weights(::SimpleDiGraph{Int64})
Closest candidates are:
  weights(::AbstractGraph) at ~/Graphs.jl/src/core.jl:422
Stacktrace:
 [1] longest_path(g::SimpleDiGraph{Int64})
   @ Main.Graphs ~/Graphs.jl/src/new_algorithm/new_algorithm.jl:2
 [2] top-level scope
   @ REPL[4]:1
```

**Code demonstrating bug**
```julia
D = Graphs.DiGraph()
Graphs.add_vertex!(D)
Graphs.add_vertex!(D)
Graphs.add_vertex!(D)
Graphs.add_vertex!(D)
Graphs.add_edge!(D, 1, 2)
Graphs.add_edge!(D, 2, 3)
Graphs.add_edge!(D, 2, 4)
Graphs.add_edge!(D, 3, 4)
return D
```

**Version information**
 - output from `versioninfo()` surrounded by backticks (``):
`
Julia Version 1.8.4
Commit 00177ebc4fc (2022-12-23 21:32 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 20 × 12th Gen Intel(R) Core(TM) i7-12700H
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, goldmont)
  Threads: 1 on 20 virtual cores
`
 - output from `] status Graphs` surrounded by backticks (``):
`Project Graphs v1.7.4
No Matches in ~/Graphs.jl/Project.toml
`

**Additional context**
NA

**Comment by simonschoelly** [comment]
I think the problem might be this step: `julia> include('src/Graphs.jl')`.

Usually when loading a package, one this that with the `import` or `using statement`: https://docs.julialang.org/en/v1/manual/modules/#Standalone-using-and-import

The following steps work on my installation:
```julia

julia> using Graphs

julia> g = SimpleDiGraph()
{0, 0} directed simple Int64 graph

julia> weights(g)
0 × 0 default distance matrix (value = 1)
```

**Comment by matheusdiogenesandrade** [comment]
Thanks for the answer. But, as mentioned at the top of the bug report, "I am trying to implement a new algorithm for Graphs.jl". That is, I am not trying only to use its functionalities. Thus, I need some way to test if my implementation is working, and that is why I used the command `julia> include('src/Graphs.jl')`.

**Comment by matheusdiogenesandrade** [comment]
Thanks for the answer. But, as mentioned at the top of the bug report, "I am trying to implement a new algorithm for Graphs.jl". That is, I am not trying only to use its functionalities. Thus, I need some way to test if my implementation is working, and that is why I used the command `julia> include('src/Graphs.jl')`.
PS.: Closed the issue by accident.

**Comment by etiennedeg** [comment]
You should use ']dev Graphs', it will automatically create a git clone of the repository. Then, you create a branch and you can modify the repository. The files are in .julia/dev/Graphs, so you can create your file there. You just do 'use Graphs' to load the repository, and it should work

**Comment by matheusdiogenesandrade** [comment]
It worked. Thank you so much!
