### ISSUE TITLE
Implementation of `relabel_nodes`

### ISSUE THREAD

**Issue by KeishiS** [JuliaGraphs/Graphs.jl#225]
Graphs.jl doesn't have a function such as `relabel_nodes` in NetworkX. I think the function is useful for nodes rearranging and graph shrinkage.

Would a PR for the implementation be welcome?

**Comment by hdavid16** [comment]
Graphs in this package don't have labels. Labels (metadata) can be added and modified in MetaGraphs.jl

**Comment by KeishiS** [comment]
Thank you for your reply!
I think it would be useful in `Simple(Di)Graph` if the node ids could be swapped.
The following is the simplest case:

```julia
g = SimpleDiGraph(3)
add_edge!(g, 1, 2)
add_edge!(g, 3, 1)
add_edge!(g, 3, 2)
adjacency_matrix(g)
> 3×3 SparseArrays.SparseMatrixCSC{Int64, Int64} with 3 stored entries:
>  ⋅  1  ⋅
>  ⋅  ⋅  ⋅
>  1  1  ⋅

h = SimpleDiGraph(3)
add_edge!(h, 1, 2)
add_edge!(h, 1, 3)
add_edge!(h, 2, 3)
adjacency_matrix(h)
> 3×3 SparseArrays.SparseMatrixCSC{Int64, Int64} with 3 stored entries:
>  ⋅  1  1
>  ⋅  ⋅  1
>  ⋅  ⋅  ⋅
```

`g` and `h` are isomorphic graphs except for the node ids. I would like to implement a function to obtain a graph `h` from a graph `g` and a mapping `m` like `Dict(1=>2, 2=>3, 3=>1)` .

It also makes sense to think that this function is unnecessary for Graphs.jl. Then, I will suggest it to MetaGraphs.jl.
I would like to know what you think. Thank you.

**Comment by hdavid16** [comment]
If you are building a new graph, then this would be something for this package. MetaGraphs.jl is only for storing metadata on vertices, edges, and the graph itself. There are some methods for isomorphism in Graphs.jl, but they are all experimental.

**Comment by simonschoelly** [comment]
If I understand correctly, what you are planning to do, you can already do that with `induced_subgraph` or by using `g[...]` notation, e.g.
```julia
julia> g = SimpleDiGraph([Edge(1,2), Edge(3, 1), Edge(3, 2)])
{3, 3} directed simple Int64 graph

julia> adjacency_matrix(g)
3×3 SparseArrays.SparseMatrixCSC{Int64, Int64} with 3 stored entries:
 ⋅  1  ⋅
 ⋅  ⋅  ⋅
 1  1  ⋅

julia> h = g[[3, 2, 1]]
{3, 3} directed simple Int64 graph

julia> adjacency_matrix(h)
3×3 SparseArrays.SparseMatrixCSC{Int64, Int64} with 3 stored entries:
 ⋅  1  1
 ⋅  ⋅  ⋅
 ⋅  1  ⋅

```

**Comment by hdavid16** [comment]
Nice! I did not know this notation was possible.

**Comment by KeishiS** [comment]
I appreciate that you worked on this issue and shared your knowledge. I will make used of the notation.
