### ISSUE TITLE
False Arguments in doc string of save graph

### ISSUE THREAD

**Issue by leonardthomson** [JuliaGraphs/Graphs.jl#234]
In the docstring you can find an additional input `g` that doesn't exist in the definition of the function:
https://github.com/JuliaGraphs/Graphs.jl/blob/53cb58152a19ca62fa01439300948c30035dca6a/src/persistence/common.jl#L110

vs.

https://github.com/JuliaGraphs/Graphs.jl/blob/53cb58152a19ca62fa01439300948c30035dca6a/src/persistence/common.jl#L118-L120

No big mistake, but little confusing and easy to fix.
Thank you!

**Comment by aurorarossi** [comment]
Thank you for pointing that out!
