### ISSUE TITLE
Add `hermitian adjacency matrix`

### ISSUE THREAD

**Issue by KeishiS** [JuliaGraphs/Graphs.jl#236]
I’d like to implement `hermitian adjacency matrix` and some associated functions.
Hermitian adjacency matrix has been proposed in [Liu & Li (2015)](https://www.sciencedirect.com/science/article/pii/S0024379514006971?via%3Dihub) and these days the matrix is used by various methods, especially spectral clustering algorithms for digraph.
e.g. [Cucuringu, Li, Sun, & Zanetti (2019)](https://arxiv.org/pdf/1908.02096.pdf), [Laenen & Sun (2020)](https://nips.cc/virtual/2020/poster/18735)

I'd like to get these matrices through major library. Would it be welcome?

## Definitions

In a graph $G$ with $n$ nodes, the simple hermitian adjacency matrix $A\in \mathbb{C}^{N\times N}$ of $G$ is the complex-valued matrix defined as following:

$$
\begin{aligned}
A_{u,v} = \begin{cases}
1 & u \rightsquigarrow v \quad\\&\quad v \rightsquigarrow u
\\
i & u \rightsquigarrow v \quad \\&\quad v \not\rightsquigarrow u
\\
-i & u \not\rightsquigarrow v \quad\\&\quad v \rightsquigarrow u
\\
0 & \text{o.w.}
\end{cases}
\end{aligned}
$$

```julia
julia> dg = SimpleDiGraph([Edge(1, 2), Edge(1, 3), Edge(3, 2)])
{3, 3} directed simple Int64 graph

julia> adjacency_matrix(dg)
3×3 SparseArrays.SparseMatrixCSC{Int64, Int64} with 3 stored entries:
 ⋅  1  1
 ⋅  ⋅  ⋅
 ⋅  1  ⋅

julia> sparse([0 im im; -im 0 -im; -im im 0]) # hermitian adjacency matrix
3×3 SparseMatrixCSC{Complex{Int64}, Int64} with 6 stored entries:
   ⋅    0+1im  0+1im
 0-1im    ⋅    0-1im
 0-1im  0+1im    ⋅
```

**Comment by simonschoelly** [comment]
@KeishiS sorry for the late answer. I am not (yet) familiar with these matrices/functions, but I would they would be a welcome addition. 

Unfortunately, people maintaining this package are quite busy, so everything is moving at a glacial pace at the moment, so if you open a PR it can take quite a while to get a response.

**Comment by KeishiS** [comment]
Thanks for your reply. First of all, I'm glad to receive your positive feedback. I understand that you maintainers are very busy. I'll submit a PR as soon as possible, but there's no need to review it quickly. I'd appreciate it if you could do so when you have free time.

**Comment by KeishiS** [comment]
I found that there are several definitions for a hermitian adjacency matrix. At the moment, I'm not sure which definition is better. As I plan to work on this again after further research in this area, I close this issue.
