### ISSUE TITLE
Add Mycielskian construction

### ISSUE THREAD

**Issue by pgrepds** [JuliaGraphs/Graphs.jl#238]
A hereditary family $\mathcal{G}$ of graphs is $\chi$-bounded with $\chi$-binding function $f: \mathbb{N} \to \mathbb{N}$ if $\chi(G) \leq f(\omega(G))$ for all $G$ in $\mathcal{G}$. A classical result of Erdős shows that the gap between the clique number and the chromatic number of a graph can be arbitrarily large. Multiple interesting research questions arise from this result. The most prominent one asks: when is a family of graphs $\chi$-bounded?

The most famous construction that yields a triangle-free graph with an arbitrary large chromatic number is the [Mycielskian construction](https://en.wikipedia.org/wiki/Mycielskian). Obviously, a consequence of this result is that not all graph families are $\chi$-bounded. The Mycielskian contruction is therefore often used as a counterexample in this field of study. Thus, it would make sense to include this graph family as a static construction in `Graphs.jl` (`staticgraphs.jl`) and the [Grötzsch graph](https://en.wikipedia.org/wiki/Grötzsch_graph) (3rd Mycielskian)  (in `small graphs.jl`).

I'd like to implement both in `Graphs.jl`, if there is nothing against it.

**Comment by aurorarossi** [comment]
Hello!  There is already an open pull request (https://github.com/JuliaGraphs/Graphs.jl/pull/177) for the `mycielski` operator.

**Comment by Krastanov** [comment]
reopening the issue as that pr has stalled and it would be nice to keep this tracked
