### ISSUE TITLE
Add support for iterating over edges in a particular order

### ISSUE THREAD

**Issue by jlapeyre** [JuliaGraphs/Graphs.jl#242]
I don't think this is done yet.

For example for this graph:
```julia
function make_dag()
    g = SimpleDiGraph(4)
    add_edge!(g, 4, 1)
    add_edge!(g, 1, 2)
    add_edge!(g, 2, 3)
    add_edge!(g, 1, 3)
    return g
end
```

You would have this.
```julia
julia> dag = make_dag()
{4, 4} directed simple Int64 graph

julia> collect(edges(dag))
4-element Vector{Graphs.SimpleGraphs.SimpleEdge{Int64}}:
 Edge 1 => 2
 Edge 1 => 3
 Edge 2 => 3
 Edge 4 => 1

julia> collect(edges_topological(dag))
4-element Vector{Any}:
 Edge 4 => 1
 Edge 1 => 2
 Edge 1 => 3
 Edge 2 => 3
```
If the ordering is done at the granularity of first vertex in an edge (that is for fixed first vertex, the second
may not be in the requested order) you can get the above with the following. I didn't check yet that the types are restricted to those following the assumptions I've made. Furthermore, the ordering of vertices is assumed to be indexable here.
```julia
struct EdgesOrdered{Order, GT, VT}
    graph::GT
    verts::VT
end

EdgesOrdered(graph, verts) = EdgesOrdered{nothing, typeof(graph), typeof(verts)}(graph, verts)
EdgesOrdered(order, graph, verts) = EdgesOrdered{order, typeof(graph), typeof(verts)}(graph, verts)

function Base.show(io::IO, eos::EdgesOrdered{GT, VT, Order}) where {GT, VT, Order}
    if isnothing(Order)
        print(io, "EdgesOrdered{$GT, $VT}(nv=$(Graphs.nv(eos.graph)), ne=$(Graphs.ne(eos.graph)))")
    else
        print(io, "EdgesOrdered{$GT, $VT, $Order}(nv=$(Graphs.nv(eos.graph)), ne=$(Graphs.ne(eos.graph)))")
    end
end

Base.IteratorSize(et::Type{<:EdgesOrdered}) = Base.HasLength()
Base.length(et::EdgesOrdered) = Graphs.ne(et.graph)

function Base.iterate(et::EdgesOrdered, (i, j)=(1, 1))
    overts = outneighbors(et.graph, et.verts[i])
    while j > length(overts)
        j = 1
        i += 1
        i > length(et.verts) && return nothing
        overts = outneighbors(et.graph, et.verts[i])
    end
    return (edgetype(et.graph)(et.verts[i], overts[j]), (i, j+1))
end

function edges_topological(graph::AbstractSimpleGraph)
    verts = topological_sort(graph)
    return EdgesOrdered{:Topological, typeof(graph), typeof(verts)}(graph, verts)
end
```

**Comment by gdalle** [comment]
Why does this need to be in the base library? I think it's nice that users can implement it in a few lines of code like you did

**Comment by jlapeyre** [comment]
A week after opening this issue, I did [put this in a package](https://github.com/jlapeyre/GraphsExt.jl/blob/4741a31508dee6e46c89263e2adb7e6ddea1644e/src/GraphsExt.jl#L57-L60).

If it turned out to be a popular feature (it is for me) it would be worth considering moving it into the base library. Or if there is `Graphs` and `GraphsBase` in the future, maybe it would go in `Graphs`.

Discoverability is a potential problem. But if it is discoverable and no one uses it, then obviously putting it in `Graphs` would be a bad idea.
