### ISSUE TITLE
`issymmetric(::SimpleDiGraph)` not correct

### ISSUE THREAD

**Issue by jlapeyre** [JuliaGraphs/Graphs.jl#248]
This dispatches here
https://github.com/JuliaGraphs/Graphs.jl/blob/53cb58152a19ca62fa01439300948c30035dca6a/src/operators.jl#L498

This of course returns false for any digraph, and digraphs can indeed be symmetric.

I don't know how many meanings of `symmetric` are common in fields using graphs. But wikipedia says this means that for each edge $(v, w)$ there is an edge $(w, v)$.

**Comment by simonschoelly** [comment]
I agree with you here. I think if we change it, we have to do it, so that it is still true for all undirected graphs. For directed graphs I am not sure if there is an easy way to that so have some default for all directed `AbstractGraph` or if we simply should return a not-implemented message.

**Comment by etiennedeg** [comment]
Should it also take into account weights or metadata ?

**Comment by gdalle** [comment]
But Graphs.jl itself doesn't have a method for getting the weight of an edge. Best we could do is to add an optional argument `weights` passing a matrix? But who would ever use this function anyway?

**Comment by simonschoelly** [comment]
> Should it also take into account weights or metadata ?

I think the solution that we currently have in #248 kind of solves this, although certainly there are other ways to handle that. It basically uses the `edges(g)`, `reverse(e)`, `has_edge(g, e)`, and `e1 == e2` functions to verify if a graph is symmetric. If some graph type  has some weights/edge-metadata and correctly implements these functions, then symmetry is correctly checked.

Of course one could argue, that there should be a way to ignore weights/metadata but I am not sure how important that is. perhaps in the future, we can specify that with an additional parameter.
