### ISSUE TITLE
Add Aqua badge to README

### ISSUE THREAD

**Issue by gdalle** [JuliaGraphs/Graphs.jl#256]

**Comment by simonschoelly** [comment]
Sorry to be a bit negative here, but I think just adding too many batches that don't provide any information when clicking on them does not provide any benefit to the users. But as it has already been merge, lets keep it that way.

**Comment by gdalle** [comment]
In light of the recent discourse discussions on package quality requirements, I thought it was a good idea to showcase some standards that we hold ourselves to?

**Comment by gdalle** [comment]
Especially since Graphs.jl already has many flaws and lacks sustained maintenance, so in terms of image my guess is it cannot hurt
