### ISSUE TITLE
[Question] How to add distances to graph edges?

### ISSUE THREAD

**Issue by ejmeitz** [JuliaGraphs/Graphs.jl#259]
This might have an obvious answer but is there a simple way to add the weight/distance of an edge between two nodes when you insert it into the graph? It does not look like there is a version of `add_edge!` that has this feature and I do not see a discussion of it in the shorted path algorithms. Could someone point me to docs that explain how I can do this.

I see the docs on making a distance matrix but is there not a way to add this information to the graph structure on construction so I don't have to carry this extra matrix around manually.

**Comment by gdalle** [comment]
Hi @ejmeitz,
Indeed, the basic `SimpleGraph` structure provided by Graphs.jl is for unweighted graphs. We are currently working on a more generic interface, but in the meantime, check out [SimpleWeightedGraphs.jl](https://github.com/JuliaGraphs/SimpleWeightedGraphs.jl) for graphs with edge weights
