### ISSUE TITLE
New centrality tests are failing

### ISSUE THREAD

**Issue by gdalle** [JuliaGraphs/Graphs.jl#285]
The new centrality tests introduced by #272 seem to be responsible for CI failures in #268 (sorry @Dolgalad).
@simonschoelly any clue about this?

**Comment by simonschoelly** [comment]
I did not have time to look deeply into it, but I doubt that #272 is responsible for this, as tests have passed before.

**Comment by gdalle** [comment]
Ok, then it's probably the modification to Dijkstra that is to blame
