### ISSUE TITLE
[BUG] 404 on link to docs

### ISSUE THREAD

**Issue by NAThompson** [JuliaGraphs/Graphs.jl#292]
**Description of bug**

The documentation link (juliagraphs/Graphs.jl) from this github page 404's:

**How to reproduce**

Click here: [juliagraphs.org/Graphs.jl](https://juliagraphs.org/Graphs.jl)

<img width="647" alt="Screenshot 2023-08-11 at 09 35 01" src="https://github.com/JuliaGraphs/Graphs.jl/assets/5459618/369a8d30-9c74-4a87-9a92-0c04cea037cd">

Low priority . . .

**Comment by etiennedeg** [comment]
I made a quick fix by adding `dev/` to the url. Maybe we could redirect the main url to this url.

**Comment by gdalle** [comment]
Not sure how we can do that? It works automatically for GitHub-hosted websites but for the custom domain `juliagraphs.org` it probably needs manual intervention. Who among us has access to it? @simonschoelly
