### ISSUE TITLE
Girvan–Newman algorithm for community detection

### ISSUE THREAD

**Issue by leerosenthalj** [JuliaGraphs/Graphs.jl#298]
Would it be possible to implement the [Girvan-Newman algorithm](https://en.wikipedia.org/wiki/Girvan%E2%80%93Newman_algorithm) for community detection? It would be a useful addition to the existing community detection algorithms in the Graphs module.

**Comment by gdalle** [comment]
Of course, but developer time is rather limited at the moment. Feel free to submit a PR if you wanna take a crack at it, we'll try to help :)

**Comment by leerosenthalj** [comment]
I'd be happy to take a shot! I will give it some effort in the next month after completing some time-sensitive work.

**Comment by gdalle** [comment]
Closing in favor of https://github.com/JuliaGraphs/Graphs.jl/issues/231

**Comment by tecosaur** [comment]
(I think you forgot to hit the "close" button :stuck_out_tongue:)
