### ISSUE TITLE
[BUG] mincut() gives wrong result

### ISSUE THREAD

**Issue by axsk** [JuliaGraphs/Graphs.jl#324]
Attempting to use the `mincut()` in todays advent of code problem I had to discover that it was not actually finding the min-cut.

The provided graph has a min-cut of 3 edges. `mincut()` on the other side returns another cut with 4 edges.

The following excerpt computes the true min-cut via `karger_min_cut`, and also computes the wrong one with `mincut()` of length 4.

```julia
function test_mincut()
    g, nodes = parseinput(readlines("25.in"))
    while true
        cut = karger_min_cut(g)
        length(karger_cut_edges(g, cut)) == 3 && break
    end

    cut2, _ = mincut(g)
    @show cut == cut2
    @show length.(karger_cut_edges.(Ref(g), [cut, cut2]))
end
```
The whole code+graph data (file `25.in`) can be found [here](https://github.com/axsk/advent-of-code/blob/main/2023/25.jl).

Julia 1.10rc3 with Graphs 1.9.0.

**Comment by Moelf** [comment]
I have found that:
- https://juliagraphs.org/Graphs.jl/dev/algorithms/cut/#Graphs.karger_cut_edges-Union{Tuple{T}, Tuple{AbstractGraph{T}, Vector{<:Integer}}} where T<:Integer

can over estimate the number of graphs as well, for my input I see occasional `760, 790` while the curret answer should be `759, 791`  (for size of the nodes in `1` and `2`)

**Comment by gdalle** [comment]
Thank you for filing the issue! It seems you wrote your [own version of `mincut`](https://github.com/axsk/advent-of-code/blob/main/2023/25%20sw.jl) instead? Could you explain what you changed to fix it?

**Comment by gdalle** [comment]
Related: #105

**Comment by axsk** [comment]
I ported the first C++ implementation from [Wikipedia](https://en.wikipedia.org/wiki/Stoer%E2%80%93Wagner_algorithm#Example_code) (seem pretty solid and nice to me).
They keep all state in a single copy of the weight matrix, doing the vertex-merging by weight updates.

I tried crosschecking it with the packages `mincut` but could not really align them.
Especially [L77](https://github.com/JuliaGraphs/Graphs.jl/blob/da6f8013d7794c57fe31d04bca720fca64f0d7cf/src/traversals/maxadjvisit.jl#L76) I still don't understand (in the classical Stoer Wagner edge weights increase only). Then there is the new [additional vertex merge](https://github.com/JuliaGraphs/Graphs.jl/blob/da6f8013d7794c57fe31d04bca720fca64f0d7cf/src/traversals/maxadjvisit.jl#L87C16-L87C24)
