### ISSUE TITLE
Question regarding `non_backtracking_matrix` function's return type

### ISSUE THREAD

**Issue by KeishiS** [JuliaGraphs/Graphs.jl#326]
Thank you for your ongoing development efforts.
I have a question concerning the `non_backtracking_matrix` function. I noticed it returns a non-sparse matrix, whereas the `adjacency_matrix` function returns a sparse matrix. Can I ask you for some insight into the reasons behind this choice?

If there's no specific reason for using a non-sparse matrix, I'd love to submit a pull request to modify the function so that it returns a sparse matrix.

Thanks for your time!

**Comment by gdalle** [comment]
I don't think there is a reason for it not to be sparse, feel free to submit a PR fixing it! Review may take a while but if the PR is simple enough we shouldn't have any issues
