### ISSUE TITLE
Incorrect documentation for `dfs_tree`.

### ISSUE THREAD

**Issue by iago-lito** [JuliaGraphs/Graphs.jl#366]
https://github.com/JuliaGraphs/Graphs.jl/blob/bf9544bca1c154e9e31decc4b149d2de96970bf6/src/traversals/dfs.jl#L84-L89

The function does not return a vector of vertices but a graph. Also, it does accept a `dir` keyword argument, just like `bfs_tree`.

**Comment by gdalle** [comment]
Good catch! Do you want to submit a documentation PR to fix it?

**Comment by gdalle** [comment]
Closed by #367
