### ISSUE TITLE
dorogovtsev_mendes graph generator is running in O(n^2)

### ISSUE THREAD

**Issue by AntoineBut** [JuliaGraphs/Graphs.jl#370]
Generating a graph of size N using the[ dorogovtsev_mendes algorithm](https://arxiv.org/pdf/cond-mat/0106144.pdf#page=24) should run in $O(N)$ and not $O(N^2)$. (see [source](https://github.com/JuliaGraphs/Graphs.jl/blob/0fa5f52856f7f779e8f2ca49bc6cee26e5e19b50/src/SimpleGraphs/generators/randgraphs.jl#L1455-L1481))

I actually don't really understand why this has been implemented this way, and I can try to make a more efficient implementation.

**Comment by gdalle** [comment]
that would be a welcome contribution, thanks!
