### ISSUE TITLE
[OPTIM] perm_greedy_color (and thus all coloring algorithms) is running in O(n^2) instead of O(n)

### ISSUE THREAD

**Issue by AntoineBut** [JuliaGraphs/Graphs.jl#378]
It shouldn't. 

Internal method uses a Vector instead of a Set, profiling shows 90+% of time is spent on emptying that vector between iterations:
 
![Capture d'écran 2024-05-26 185352](https://github.com/JuliaGraphs/Graphs.jl/assets/90978814/54c2a2a8-c4ec-4f67-b5e6-c6bb8142f669)

**Comment by gdalle** [comment]
Fixed by #379
