### ISSUE TITLE
[BUG] Can't add vertices to a `MetaDiGraph`

### ISSUE THREAD

**Issue by caseykneale** [JuliaGraphs/Graphs.jl#38]
Run this,
```julia
using LightGraphs, MetaGraphs, SimpleGraphs

g = MetaDiGraph()

add_vertex!(g.graph)
add_edge!(g,1,1)
```
and then make a new session swapping LightGraphs for Graphs.jl
you should get the following error:
```
ERROR: LoadError: MethodError: no method matching add_vertex!(::LightGraphs.SimpleGraphs.SimpleDiGraph{Int64})
Closest candidates are:
  add_vertex!(::SimpleDiGraph{T}) where T at /home/caseykneale/.julia/packages/Graphs/Mih78/src/SimpleGraphs/simpledigraph.jl:449
  add_vertex!(::Graphs.SimpleGraphs.SimpleGraph{T}) where T at /home/caseykneale/.julia/packages/Graphs/Mih78/src/SimpleGraphs/simplegraph.jl:526
  ```

**Comment by etienneINSA** [comment]
I can't reproduce the error. Make sure you have upgraded MetaGraphs to the latest version, and that you don't load LightGraphs (eg. in you startup.jl). Also, note that SimpleGraphs.jl is a totally separate package from Graphs.jl.
Let me know if you still get the error.

**Comment by caseykneale** [comment]
I tried updating all packages and ran it again with the same result. I probably wasn't very clear in my original post, sorry. Doing this:
``julia
using Graphs, MetaGraphs, SimpleGraphs

g = MetaDiGraph()

add_vertex!(g.graph)
add_edge!(g,1,1)
```
results in the error shown above. Doing this,
```julia
using LightGraphs, MetaGraphs, SimpleGraphs

g = MetaDiGraph()

add_vertex!(g.graph)
add_edge!(g,1,1)
```
works as expected.

If this is working for you (not on master) let me know, then its a compat issue or something goofy. Or I could be misunderstanding the scope of Graphs.jl, I haven't been following the developments at all(unfortunately). Either way, this error occurred on one of my packages after someone added the Graphs.jl dependency in favor of LightGraphs.

**Comment by etiennedeg** [comment]
LightGraphs is not used anywhere now in the codebase of MetaGraphs and Graphs, so this is weird. What do you get with `] status MetaGraphs`? Is it 1.7? If not, this could be a compat issue, maybe you use a package that still uses LightGraphs and the old MetaGraphs. You can also try removing and reinstalling the packages. I also tried the issue on ParseSMILES by returning back to the old commit, and I got no problems.

**Comment by caseykneale** [comment]
Yep something is blocking me from using MetaGraphs 0.7.x . Something else was blocking ParseSMILES for me and a collaborator, I'll have to dig to see what it is. Thanks
