### ISSUE TITLE
[BUG] Compatibility issue when used alongside GraphPlot

### ISSUE THREAD

**Issue by jkhamphousone** [JuliaGraphs/Graphs.jl#391]
Hi :) I am in the process of developing my first package, and after reading [here](https://pkgdocs.julialang.org/dev/managing-packages/#conflicts-1) and trying to resolve the compatibility issue myself, I concluded that I had to report the conflict. I hope this is the write place to do it.

It looks likes GraphPlot requires ArnoldiMethod to be v0.3.0-0.6.0 or uninstalled while Graphs requires 0.4.0 — , thus no versions are left.

```julia
(@v1.10) pkg> add RingStarProblems
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package ArnoldiMethod [ec485272]:
 ArnoldiMethod [ec485272] log:
 ├─possible versions are: 0.0.1-0.4.0 or uninstalled
 ├─restricted by compatibility requirements with GraphPlot [a2cc645c] to versions: 0.0.1-0.2.0
 │ └─GraphPlot [a2cc645c] log:
 │   ├─possible versions are: 0.3.0-0.6.0 or uninstalled
 │   └─restricted to versions * by an explicit requirement, leaving only versions: 0.3.0-0.6.0
 └─restricted by compatibility requirements with Graphs [86223c79] to versions: 0.4.0 — no versions left
   └─Graphs [86223c79] log:
     ├─possible versions are: 0.10.0-1.11.2 or uninstalled
     └─restricted by compatibility requirements with RingStarProblems [bed4ad48] to versions: 1.10.0-1.11.2
       └─RingStarProblems [bed4ad48] log:
         ├─possible versions are: 0.1.0 or uninstalled
         └─restricted to versions * by an explicit requirement, leaving only versions: 0.1.0

```

```
julia> versioninfo()
Julia Version 1.10.4
Commit 48d4fd48430 (2024-06-04 10:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, skylake)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
```

Thank you a lot :)

**Comment by simonschoelly** [comment]
This seems to be an issue with GraphPlot.jl and not Graphs.jl. It looks like we restriced ArnoldiMethods.jl there to `v0.2` so we should bump that version https://github.com/JuliaGraphs/GraphPlot.jl/blob/3a7daa00e0a36b46a111fa5e270566f65d395579/Project.toml#L17 . But as there were some changes to ArnoldiMethods.jl , I think we also need to test that it still works after the version bump. Feel free to create a PR.

**Comment by jkhamphousone** [comment]
Closed in favor of issue in GraphPlot.jl
