### ISSUE TITLE
`Graphs.eulerian` doesn't seem to exist?

### ISSUE THREAD

**Issue by philschrad** [JuliaGraphs/Graphs.jl#394]
**Description of bug**
`Graphs.eulerian` doesn't seem to exist

**Code demonstrating bug**
```
using Graphs
G=SimpleGraph(Edge.([(1,2),(2,3),(1,3)]))
eulerian(G)
```
results in "UndefVarError: eulerian not defined"

**Version information**
 `- Julia Version 1.6.3
Commit ae8452a9e0 (2021-09-23 17:34 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, westmere)`
`      Status `~/.julia/environments/v1.6/Project.toml`
  [86223c79] Graphs v1.8.0`

**Comment by gdalle** [comment]
It seems you're using an old version of Graphs.jl: with the latest version it should work.

**Comment by philschrad** [comment]
🤦‍♂️ thanks!
