### ISSUE TITLE
Stress Centrality 

### ISSUE THREAD

**Issue by Sanjeevani-IITBH** [JuliaGraphs/Graphs.jl#408]
I want to know whether the code for stress centrality provided works only for simple and small graph or it is suitable for big and complex  graphs as well. Because when I am trying to implement code on 11 nodes, 28 nodes in short as i am increasing number of nodes (more than 10)  in graph this code is not giving correct stress centrality.

**Comment by simonschoelly** [comment]
Can you give give an example of such a graph here so that we ca try to reproduce the issue?

**Comment by Sanjeevani-IITBH** [comment]
Hi,

Can you please tell me if is there any update on my issue?

Thanks and Regards
