### ISSUE TITLE
Refresh icon

### ISSUE THREAD

**Issue by cormullion** [JuliaGraphs/Graphs.jl#6]
Hi graphers! (_graphistes_?) Thank you for your efforts in migrating, maintaining, and updating this package, which so many of us find useful.

As a very minor contribution, here are some suggestions for a refreshed icon.

![julia-graphs-logos](https://user-images.githubusercontent.com/52289/137704114-3dad5155-8bfc-4467-a405-807443a34502.png)

I noticed an oddity with the current icon. For some reason it's slightly transparent, which explains the subdued appearance when used with GitHub's Dark Mode.

<img width="511" alt="Screenshot 2021-10-18 at 10 22 17" src="https://user-images.githubusercontent.com/52289/137704370-9ecd601f-242e-4739-bfed-f0a68d960261.png">

The current icon also uses the OG Julia duotone colour design, which was replaced by single colours sometime around v1.2.

**Comment by ViralBShah** [comment]
I like 4 too.

**Comment by etienneINSA** [comment]
I like this one, why not illustrating graph coloration (this one is 3 colorable) ?

**Comment by jpfairbanks** [comment]
yeah if we rotate the colors on the outer square by 90deg clockwise, I think we can adopt this logo

**Comment by cormullion** [comment]
Cool, thanks! 

PNG: 

![julia-graphs](https://user-images.githubusercontent.com/52289/140908839-f2013fdf-5948-4813-8c1f-c1bfb587eaf8.png)

SVG: (zipped) 
[julia-graphs.svg.zip](https://github.com/JuliaGraphs/Graphs.jl/files/7504027/julia-graphs.svg.zip)

Code:

https://gist.github.com/cormullion/b1f11b0eaba45252a11269e893e88df5

**Comment by gdalle** [comment]
So should we change the profile picture of the org? And perhaps add it to the documentation of Graphs.jl?

**Comment by gdalle** [comment]
I just have a question: is it just me or do the edges look slightly blurred? Is that the desired effect?

**Comment by cormullion** [comment]
Yes, the _faux_ 3D effect might look a bit blurry when seen large:

<img width="880" alt="Screenshot 2021-11-12 at 11 36 09" src="https://user-images.githubusercontent.com/52289/141461204-8f61811f-a435-4558-8d42-68bbce09be3c.png">

But it's designed to work better when icon-sized:

<img width="134" alt="Screenshot 2021-11-12 at 11 37 36" src="https://user-images.githubusercontent.com/52289/141461306-a80e39b6-693b-48b1-b02c-6221192c4761.png">

It can of course be taken to the bike-shed for further modification. 😃

**Comment by cormullion** [comment]
Awesome, thanks!
