### ISSUE TITLE
[Port] [BUG] `adjacency_matrix` fails for `SimpleGraph` with self-loops (Julia 1.7)

### ISSUE THREAD

**Issue by gdalle** [JuliaGraphs/Graphs.jl#67]
See https://github.com/sbromberger/LightGraphs.jl/issues/1594

**Comment by etienneINSA** [comment]
Fixed by [#15 ](https://github.com/JuliaGraphs/Graphs.jl/pull/15)

**Comment by gdalle** [comment]
@etienneINSA what is the rationale of allowing loops in a SimpleGraph? I'm all for a more explicit error message, but shouldn't this be forbidden from the start?

**Comment by etienneINSA** [comment]
In my understanding, SimpleGraphs (in the context of this library) allow self-loops (but no multiple edges), but I may be wrong... @jpfairbanks ?
If not, there is some work as there are no checks anywhere, and I have already encountered functions in the library which return graphs with self-loops.

**Comment by simonschoelly** [comment]
Self-loops where at one point allowed on purpose. And I would agree, while the strict mathematical definition of a simple graph does not allow self-loops, it is a nice feature to have.

One downside of that is though, that it adds additional edge cases that have to be checked for some algorithms.

**Comment by simonschoelly** [comment]
Fixed by #15
