### ISSUE TITLE
[Port] Use `ismutable` in `johnson_shortest_paths`

### ISSUE THREAD

**Issue by gdalle** [JuliaGraphs/Graphs.jl#68]
See https://github.com/sbromberger/LightGraphs.jl/issues/1597

**Comment by simonschoelly** [comment]
Note that `ismutable` is only available from Julia v1.5 on. Therefore one should either use `ismutable` from [Compat.jl](https://github.com/JuliaLang/Compat.jl) or create a method that checks for the Julia version and acts accordingly.

And while someone is on that, maybe they can also replace this line https://github.com/JuliaGraphs/Graphs.jl/blob/761912f62854a22129b485d5cdc7515d03b1ee85/src/shortestpaths/johnson.jl#L38 with one that uses `isa`.

**Comment by simonschoelly** [comment]
Solved by 574897abd6edc1fde0d54e22c4aead8f516e02a6
