### ISSUE TITLE
Non-deterministic test failure in closness centrality

### ISSUE THREAD

**Issue by ViralBShah** [JuliaGraphs/Graphs.jl#7]
I saw this once on my mac running single threaded

```
 Testing Running tests...
Parallel.Closeness: Test Failed at /Users/viral/.julia/packages/Graphs/mjncd/test/parallel/centrality/closeness.jl:14
  Expression: tz ≈ [0.75, 0.4444444444444444, 0.3333333333333333, 0.0]
   Evaluated: [0.75, 0.4444444444444444, 0.3333333333333333, NaN] ≈ [0.75, 0.4444444444444444, 0.3333333333333333, 0.0]
Stacktrace:
 [1] macro expansion
   @ ~/.julia/packages/Graphs/mjncd/test/parallel/centrality/closeness.jl:14 [inlined]
 [2] macro expansion
   @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
 [3] top-level scope
   @ ~/.julia/packages/Graphs/mjncd/test/parallel/centrality/closeness.jl:2
```

And see it in CI too: https://github.com/JuliaGraphs/Graphs.jl/runs/3931288326

**Comment by jpfairbanks** [comment]
This looks like a difference between Serial and Parallel initialization

Serial code initializes using `zeros` https://github.com/JuliaGraphs/Graphs.jl/blob/d1359194e56ae505b8617c2aa7e5ab93289b8c9a/src/centrality/closeness.jl#L37

The parallel code initializes to `undef`

https://github.com/JuliaGraphs/Graphs.jl/blob/d1359194e56ae505b8617c2aa7e5ab93289b8c9a/src/Parallel/centrality/closeness.jl#L37

Manual memory management is bad. Is there a reason not to use `zeros` with threads?

**Comment by simonschoelly** [comment]
On the other hand, this highlight the problem that the centrality is assigned for some vertices in digraphs. One should study the definition of closeness centrality and figure out if assigning zero in that case is indeed the right thing to do.

**Comment by jpfairbanks** [comment]
Yeah I think the immediate fix is to match the serial code. That wikipedia article that we cite assumes that the graph is symmetric, and provides this warning 

> Taking distances from or to all other nodes is irrelevant in undirected graphs, whereas it can produce totally different results in directed graphs (e.g. a website can have a high closeness centrality from outgoing link, but low closeness centrality from incoming links).

We should probably patch the parallel version to not be wrong and then support proper distances for directed graphs. We probably need to support both orientations.
